FROM ubuntu:20.04 as base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y cmake make g++ git python3-dev python3-numpy python3-pip libssl-dev

RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install --upgrade scikit-build cmake requests pytest

ADD . /usr/local/src/htm.core
WORKDIR /usr/local/src/htm.core
RUN python3 setup.py install


FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y python3 python3-numpy python3-pip

COPY --from=base /usr/local/lib/python3.8 /usr/local/lib/python3.8
